version: 2
sources:
  - name: dbt_meder_bike
    tables:
      - name: bike_duration
        columns:
          - name: bike_id
          - name: start_date
          - name: trip_count_last_week
          - name: trip_duration_last_week
      - name: bike_is_winner
        columns:
          - name: bike_id
          - name: date
          - name: is_winner
        meta:
          fal:
            feature_store:
              entity_column: bike_id
              timestamp_column: date
  - name: samples
    tables:
      - name: bike_dataset_labels_maintenance_required
        columns:
          - name: bike_id
          - name: timestamp

models:
  - name: bike_duration
    columns:
      - name: trip_count_last_week
      - name: trip_duration_last_week
      - name: bike_id
      - name: start_date
    meta:
      fal:
        feature_store:
          entity_column: bike_id
          timestamp_column: start_date
